name: 💡 Feature Request
description: Suggest an idea or enhancement for this project
labels: [ "Needs triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this report!
        This form is meant to be used to suggest an idea or enhancement for this project.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search the history](https://github.com/muffi/couleurbummel/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: This is not a data update request
      description: Please use the in-app functionality to request data updates or additions.
      options:
        - label: I am not requesting a data update
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: If yes, please describe the problem you'd like to see solved.
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you would like to see happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you considered.
  - type: textarea
    attributes:
      label: Additional context
      render: Markdown
      description: |
        Add any other context or screenshots about the feature request here
